name: Tests (TDD)

on: push

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install necessary dependencies
        run: npm install
      - name: Running all of the tests
        run: npm test
